### ISSUE TITLE
Script fails with proxy

### ISSUE THREAD

**Issue by ucakmakci** [v-zhuravlev/zabbix-weather#1]
Hi,

Script fails while using proxy!
################################################################################
[root@host]# ./get_weather.pl -lat 55.672944 -lon 38.478944 --hostname test --api_key xxxxxxxxxxxxxxxxx
500 Can't connect to api.openweathermap.org:80 (timeout)
################################################################################

################################################################################
 wget api.openweathermap.org/data/2.5/forecast/city?id=524901&APPID=xxxxxxxxxxxxxxxxx
Proxy request sent, awaiting response... 401 Unauthorized
Authorization failed.
################################################################################

I assume this problem happens because of double quote 

################################################################################
wget "api.openweathermap.org/data/2.5/forecast/city?id=524901&APPID=xxxxxxxxxxxxxxxxx"
Connecting to xx.xx.xx.xx:8080... connected.
Proxy request sent, awaiting response... 200 OK
################################################################################

Can you fix

**Comment by v-zhuravlev** [comment]
Hi,  
- what double quote are you talking about?
- The script doesn't use any proxy at the moment so it was an attempt to connect directly I suppose.

**Comment by v-zhuravlev** [comment]
Do you use any environment variables for wget? like `http_proxy` or something?

**Comment by v-zhuravlev** [comment]
Added proxy support. Try new script from here:
https://github.com/v-zhuravlev/zabbix-weather/tree/proxy_support
Please tell me if it works

**Comment by ucakmakci** [comment]
Thanks for the quick reply
[root@host]# export http_proxy=xx.xx.xx.xx:8080
[root@host]# ./get_weather.pl -lat 55.672944 -lon 38.478944 --hostname test --api_key xxxxxxxxxxxxxxxxx
Proxy must be specified as absolute URI; 'xx.xx.xx.xx:8080' is not at ./get_weather.pl line 150.

**Comment by v-zhuravlev** [comment]
try export http_proxy=http://xx.xx.xx.xx:8080/

**Comment by ucakmakci** [comment]
[root@host]# ./get_weather.pl -lat 55.672944 -lon 38.478944 --hostname test --api_key xxxxxxxxxxxxxxxxx
OK

Thank you very much 
it is running it seems

**Comment by v-zhuravlev** [comment]
You are welcome, thanks for requesting
